module.exports = [
    {code: "en", country: "English"},
    {code: "de", country: "German"},
    {code: "fr", country: "French"},
    {code: "sq_AL", country: "Albanian (Albania)"},
    {code: "sq", country: "Albanian"},
    {code: "ar_DZ", country: "Arabic (Algeria)"},
    {code: "ar_BH", country: "Arabic (Bahrain)"},
    {code: "ar_EG", country: "Arabic (Egypt)"},
    {code: "ar_IQ", country: "Arabic (Iraq)"},
    {code: "ar_JO", country: "Arabic (Jordan)"},
    {code: "ar_KW", country: "Arabic (Kuwait)"},
    {code: "ar_LB", country: "Arabic (Lebanon)"},
    {code: "ar_LY", country: "Arabic (Libya)"},
    {code: "ar_MA", country: "Arabic (Morocco)"},
    {code: "ar_OM", country: "Arabic (Oman)"},
    {code: "ar_QA", country: "Arabic (Qatar)"},
    {code: "ar_SA", country: "Arabic (Saudi Arabia)"},
    {code: "ar_SD", country: "Arabic (Sudan)"},
    {code: "ar_SY", country: "Arabic (Syria)"},
    {code: "ar_TN", country: "Arabic (Tunisia)"},
    {code: "ar_AE", country: "Arabic (United Arab Emirates)"},
    {code: "ar_YE", country: "Arabic (Yemen)"},
    {code: "ar", country: "Arabic"},
    {code: "be_BY", country: "Belarusian (Belarus)"},
    {code: "be", country: "Belarusian"},
    {code: "bg_BG", country: "Bulgarian (Bulgaria)"},
    {code: "bg", country: "Bulgarian"},
    {code: "ca_ES", country: "Catalan (Spain)"},
    {code: "ca", country: "Catalan"},
    {code: "zh_CN", country: "Chinese (China)"},
    {code: "zh_HK", country: "Chinese (Hong Kong)"},
    {code: "zh_SG", country: "Chinese (Singapore)"},
    {code: "zh_TW", country: "Chinese (Taiwan)"},
    {code: "zh", country: "Chinese"},
    {code: "hr_HR", country: "Croatian (Croatia)"},
    {code: "hr", country: "Croatian"},
    {code: "cs_CZ", country: "Czech (Czech Republic)"},
    {code: "cs", country: "Czech"},
    {code: "da_DK", country: "Danish (Denmark)"},
    {code: "da", country: "Danish"},
    {code: "nl_BE", country: "Dutch (Belgium)"},
    {code: "nl_NL", country: "Dutch (Netherlands)"},
    {code: "nl", country: "Dutch"},
    {code: "en_AU", country: "English (Australia)"},
    {code: "en_CA", country: "English (Canada)"},
    {code: "en_IN", country: "English (India)"},
    {code: "en_IE", country: "English (Ireland)"},
    {code: "en_MT", country: "English (Malta)"},
    {code: "en_NZ", country: "English (New Zealand)"},
    {code: "en_PH", country: "English (Philippines)"},
    {code: "en_SG", country: "English (Singapore)"},
    {code: "en_ZA", country: "English (South Africa)"},
    {code: "en_GB", country: "English (United Kingdom)"},
    {code: "en_US", country: "English (United States)"},
    {code: "et_EE", country: "Estonian (Estonia)"},
    {code: "et", country: "Estonian"},
    {code: "fi_FI", country: "Finnish (Finland)"},
    {code: "fi", country: "Finnish"},
    {code: "fr_BE", country: "French (Belgium)"},
    {code: "fr_CA", country: "French (Canada)"},
    {code: "fr_FR", country: "French (France)"},
    {code: "fr_LU", country: "French (Luxembourg)"},
    {code: "fr_CH", country: "French (Switzerland)"},
    {code: "de_AT", country: "German (Austria)"},
    {code: "de_DE", country: "German (Germany)"},
    {code: "de_LU", country: "German (Luxembourg)"},
    {code: "de_CH", country: "German (Switzerland)"},
    {code: "el_CY", country: "Greek (Cyprus)"},
    {code: "el_GR", country: "Greek (Greece)"},
    {code: "el", country: "Greek"},
    {code: "iw_IL", country: "Hebrew (Israel)"},
    {code: "iw", country: "Hebrew"},
    {code: "hi_IN", country: "Hindi (India)"},
    {code: "hu_HU", country: "Hungarian (Hungary)"},
    {code: "hu", country: "Hungarian"},
    {code: "is_IS", country: "Icelandic (Iceland)"},
    {code: "is", country: "Icelandic"},
    {code: "in_ID", country: "Indonesian (Indonesia)"},
    {code: "in", country: "Indonesian"},
    {code: "ga_IE", country: "Irish (Ireland)"},
    {code: "ga", country: "Irish"},
    {code: "it_IT", country: "Italian (Italy)"},
    {code: "it_CH", country: "Italian (Switzerland)"},
    {code: "it", country: "Italian"},
    {code: "ja_JP", country: "Japanese (Japan)"},
    {code: "ja_JP_JP", country: "Japanese (Japan},JP)"},
    {code: "ja", country: "Japanese"},
    {code: "ko_KR", country: "Korean (South Korea)"},
    {code: "ko", country: "Korean"},
    {code: "lv_LV", country: "Latvian (Latvia)"},
    {code: "lv", country: "Latvian"},
    {code: "lt_LT", country: "Lithuanian (Lithuania)"},
    {code: "lt", country: "Lithuanian"},
    {code: "mk_MK", country: "Macedonian (Macedonia)"},
    {code: "mk", country: "Macedonian"},
    {code: "ms_MY", country: "Malay (Malaysia)"},
    {code: "ms", country: "Malay"},
    {code: "mt_MT", country: "Maltese (Malta)"},
    {code: "mt", country: "Maltese"},
    {code: "no_NO", country: "Norwegian (Norway)"},
    {code: "no_NO_NY", country: "Norwegian (Norway},Nynorsk)"},
    {code: "no", country: "Norwegian"},
    {code: "pl_PL", country: "Polish (Poland)"},
    {code: "pl", country: "Polish"},
    {code: "pt_BR", country: "Portuguese (Brazil)"},
    {code: "pt_PT", country: "Portuguese (Portugal)"},
    {code: "pt", country: "Portuguese"},
    {code: "ro_RO", country: "Romanian (Romania)"},
    {code: "ro", country: "Romanian"},
    {code: "ru_RU", country: "Russian (Russia)"},
    {code: "ru", country: "Russian"},
    {code: "sr_BA", country: "Serbian (Bosnia and Herzegovina)"},
    {code: "sr_ME", country: "Serbian (Montenegro)"},
    {code: "sr_CS", country: "Serbian (Serbia and Montenegro)"},
    {code: "sr_RS", country: "Serbian (Serbia)"},
    {code: "sr", country: "Serbian"},
    {code: "sk_SK", country: "Slovak (Slovakia)"},
    {code: "sk", country: "Slovak"},
    {code: "sl_SI", country: "Slovenian (Slovenia)"},
    {code: "sl", country: "Slovenian"},
    {code: "es_AR", country: "Spanish (Argentina)"},
    {code: "es_BO", country: "Spanish (Bolivia)"},
    {code: "es_CL", country: "Spanish (Chile)"},
    {code: "es_CO", country: "Spanish (Colombia)"},
    {code: "es_CR", country: "Spanish (Costa Rica)"},
    {code: "es_DO", country: "Spanish (Dominican Republic)"},
    {code: "es_EC", country: "Spanish (Ecuador)"},
    {code: "es_SV", country: "Spanish (El Salvador)"},
    {code: "es_GT", country: "Spanish (Guatemala)"},
    {code: "es_HN", country: "Spanish (Honduras)"},
    {code: "es_MX", country: "Spanish (Mexico)"},
    {code: "es_NI", country: "Spanish (Nicaragua)"},
    {code: "es_PA", country: "Spanish (Panama)"},
    {code: "es_PY", country: "Spanish (Paraguay)"},
    {code: "es_PE", country: "Spanish (Peru)"},
    {code: "es_PR", country: "Spanish (Puerto Rico)"},
    {code: "es_ES", country: "Spanish (Spain)"},
    {code: "es_US", country: "Spanish (United States)"},
    {code: "es_UY", country: "Spanish (Uruguay)"},
    {code: "es_VE", country: "Spanish (Venezuela)"},
    {code: "es", country: "Spanish"},
    {code: "sv_SE", country: "Swedish (Sweden)"},
    {code: "sv", country: "Swedish"},
    {code: "th_TH", country: "Thai (Thailand)"},
    {code: "th_TH_TH", country: "Thai (Thailand},TH)"},
    {code: "th", country: "Thai"},
    {code: "tr_TR", country: "Turkish (Turkey)"},
    {code: "tr", country: "Turkish"},
    {code: "uk_UA", country: "Ukrainian (Ukraine)"},
    {code: "uk", country: "Ukrainian"},
    {code: "vi_VN", country: "Vietnamese (Vietnam)"},
    {code: "vi", country: "Vietnamese"}
];
